version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - ./data/db:/var/lib/mysql
  api:
    image: localhost/lingua-card-api
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: db
